---
name: apache-kafka
vaults:
  external:
    type: filesystem
    options:
      keys:
        store: external/server/keys
        type: pkcs12
        password: generated
  internal:
    type: filesystem
    options:
      trust:
        store: internal/client/trust
        type: pkcs12
        password: generated
bindings:
  tcp_server:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port:
        - 9093
    exit: tls_server
  tls_server:
    type: tls
    kind: server
    vault: external
    options:
      keys:
      - external.net
    exit: kafka_proxy
  kafka_proxy:
    type: kafka-proxy
    kind: proxy
    options:
      external:
        host: kafka-####.external.net
        default: kafka.external.net
        port: 9093
      internal:
        host: kafka-####.internal.net
        port: 9093
    exit: tls_client
  tls_client:
    type: tls
    kind: client
    vault: internal
    options:
      trust:
      - serverca
      trustcacerts: true
    exit: tcp_client
  tcp_client:
    type: tcp
    kind: client


---
name: confluent-cloud
vaults:
  external:
    type: filesystem
    options:
      keys:
        store: external/server/keys
        type: pkcs12
        password: generated
bindings:
  tcp_server:
    type: tcp
    kind: server
    options:
      host: 0.0.0.0
      port:
        - 9092
    exit: tls_server
  tls_server:
    type: tls
    kind: server
    vault: external
    options:
      keys:
      - external.net
    exit: kafka_proxy
  kafka_proxy:
    type: kafka-proxy
    kind: proxy
    options:
      external:
        host: kafka-#-{rack}.external.net
        default: kafka.external.net
        port: 9092
      internal:
        host: CLUSTER_ID-g###-{rack}-NETWORK_ID.REGION.aws.glb.confluent.cloud
        default: CLUSTER_ID-NETWORK_ID.REGION.aws.glb.confluent.cloud
        port: 9092
    exit: tls_client
  tls_client:
    type: tls
    kind: client
    exit: tcp_client
  tcp_client:
    type: tcp
    kind: client

