[zilla-plus]
54.174.12.222 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.244 id=0

[kafka]
3.82.150.249 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.238 id=0
23.22.35.217 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.158 id=1
54.161.144.217 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.168 id=2
54.173.184.84 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.172 id=3
35.175.220.129 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.172 id=4
54.198.31.185 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.121 id=5

[controller]
34.207.69.224 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.193 id=0
18.234.132.212 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.167 id=1
54.152.6.38 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.78 id=2

[client]
52.90.104.156 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.167 id=0
54.227.53.35 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.61 id=1
54.198.255.221 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.107 id=2
44.201.246.140 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.213 id=3
184.72.64.114 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.7 id=4
18.206.196.232 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.103 id=5

[control]
52.90.104.156 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.167 id=0

[prometheus]
44.212.42.187 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.23 id=0
