[zilla-plus]
3.83.155.41 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.5 id=0

[kafka]
3.93.65.200 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.199 id=0
54.89.189.116 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.204 id=1
3.81.221.100 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.10 id=2
184.73.3.72 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.242 id=3
54.88.189.179 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.37 id=4
54.161.168.206 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.27 id=5

[controller]
3.82.108.37 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.8 id=0
52.7.240.79 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.104 id=1
3.81.88.39 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.122 id=2

[client]
54.158.133.179 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.245 id=0
52.91.49.23 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.29 id=1
54.85.168.212 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.113 id=2
18.205.114.145 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.156 id=3
52.87.221.134 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.147 id=4
35.153.183.225 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.112 id=5

[control]
54.158.133.179 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.245 id=0

[prometheus]
52.207.235.179 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.113 id=0
