[zilla-plus]
44.211.174.237 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.60 id=0

[kafka]
13.218.70.136 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.194 id=0
34.201.71.90 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.174 id=1
52.55.46.167 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.146 id=2
44.201.141.223 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.174 id=3
3.90.164.69 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.237 id=4
3.81.184.185 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.111 id=5

[controller]
54.161.102.205 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.142 id=0
54.196.216.101 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.180 id=1
100.29.8.199 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.39 id=2

[client]
3.85.32.129 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.220 id=0
54.227.32.228 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.104 id=1
54.198.193.85 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.220 id=2
3.84.194.105 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.43 id=3
54.236.99.121 ansible_user=ec2-user ansible_become=True private_ip=10.0.2.108 id=4
54.166.172.77 ansible_user=ec2-user ansible_become=True private_ip=10.0.3.167 id=5

[control]
3.85.32.129 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.220 id=0

[prometheus]
100.24.21.108 ansible_user=ec2-user ansible_become=True private_ip=10.0.1.41 id=0
