cluster.id=lkc-rov1x0
network.id=j6r2o2
region=us-east-1

bootstrap.servers=zilla.external.net:9092
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="BUL2RXGMOGH4LELK" password="AY6Io25VVct0QoPySDZyLGelRP6R5iriHlJGSn217aIHlG74oGg1WqTzkGO7ATSZ";
security.protocol=SASL_SSL
ssl.endpoint.identification.algorithm=https
request.timeout.ms=300000
max.in.flight.requests.per.connection=5
